version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
      - REDIS_PASSWORD=
      - REDIS_DB=0
      - JWT_SECRET=your-secret-key-change-in-production
    depends_on:
      - redis
    networks:
      - otp-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - otp-network

volumes:
  redis_data:

networks:
  otp-network:
    driver: bridge
